services:
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  spring-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=dummyId
      - AWS_SECRET_ACCESS_KEY=dummySecret
      - AWS_REGION=eu-west-2
      - AWS_DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
