spring:
  application:
    name: stock-info-api

app:
  limits:
    compact-records: 25
    full-records: 100
  external-api:
    url: https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=%s&apikey=%s
    token: # Token here

aws:
  dynamodb:
    region: ${AWS_REGION:eu-west-2}
    endpoint: ${AWS_DYNAMODB_ENDPOINT:}
    table-name: StockMetrics
